# Generated by Django 5.1.6 on 2025-02-27 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="类别名称")),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="图标"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "网站类别",
                "verbose_name_plural": "网站类别",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Website",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="网站名称")),
                ("url", models.URLField(verbose_name="网站地址")),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="图标"),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("clicks", models.IntegerField(default=0, verbose_name="点击次数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="websites",
                        to="navigation.category",
                        verbose_name="所属类别",
                    ),
                ),
            ],
            options={
                "verbose_name": "网站",
                "verbose_name_plural": "网站",
                "ordering": ["order", "id"],
            },
        ),
    ]
