# Generated by Django 5.1.6 on 2025-02-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="description_pinyin",
            field=models.CharField(blank=True, max_length=500, verbose_name="描述拼音"),
        ),
        migrations.AddField(
            model_name="website",
            name="name_pinyin",
            field=models.CharField(blank=True, max_length=200, verbose_name="拼音"),
        ),
    ]
