# Generated by Django 5.1.6 on 2025-02-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0002_website_description_pinyin_website_name_pinyin"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="download_path",
            field=models.CharField(blank=True, max_length=255, verbose_name="下载路径"),
        ),
        migrations.AddField(
            model_name="website",
            name="is_download",
            field=models.BooleanField(default=False, verbose_name="是否为下载链接"),
        ),
        migrations.AlterField(
            model_name="website",
            name="url",
            field=models.CharField(max_length=255, verbose_name="网站地址"),
        ),
    ]
